version: 2

project_name: lancert

before:
  hooks:
    - go test ./...

builds:
  - id: lancert
    main: ./cmd/lancert
    binary: lancert
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X go.lucor.dev/lancert-cli/internal/cli.Version={{.Version}}

archives:
  - id: lancert
    ids:
      - lancert
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  use: git
